# Generated by Django 4.1.7 on 2023-03-16 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_myprofile_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='myprofile',
            name='otp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
