# Generated by Django 4.1.7 on 2023-03-16 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_myprofile_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myprofile',
            name='otp',
        ),
        migrations.CreateModel(
            name='OtpVerifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(blank=True, max_length=100, null=True)),
                ('counter', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
