# Generated by Django 4.1.7 on 2023-03-16 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_myprofile_otp_otpverifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverifier',
            name='counter',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
