# Generated by Django 4.1.7 on 2023-02-24 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('ALL_FOOD', 'All food'), ('BAKERY', 'Bakery'), ('SEA_FOOD', 'Sea food'), ('CHICKEN', 'Chicken'), ('PIZZA', 'Pizza'), ('BURGER', 'Burger')], default='ALL_FOOD', max_length=50)),
                ('image', models.ImageField(default='default.jpg', upload_to='foods')),
                ('duration', models.DurationField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=5)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('favourite', models.BooleanField()),
                ('calorie', models.IntegerField()),
                ('about', models.TextField(max_length=500)),
            ],
        ),
    ]
